name: tester_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_screenutil: ^5.5.3+2
  http: ^1.1.0
  get_storage: ^2.1.1
  firebase_core: ^2.5.0
  firebase_messaging: ^14.2.2
  flutter_svg: ^2.0.0+1
  device_info_plus: ^9.1.0
  device_information: ^0.0.4
  cached_network_image: ^3.2.2
  shimmer: ^3.0.0
  timeline_tile: ^2.0.0
  google_fonts: ^6.1.0
  intl: ^0.18.0
  flutter_switch: ^0.3.2
  location: ^5.0.3
  slide_digital_clock: ^1.0.2
  fluttertoast: ^8.1.2
  lottie: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
  assets:
    - 'assets/images/background.png'
    - 'assets/images/background_login.png'
    - 'assets/images/splash_bg.png'
    - 'assets/images/circle_pattern.png'
    - 'assets/icons/desk_icon.png'
    - 'assets/icons/home_icon.png'
    - 'assets/lottie/empty_animation.json'
    - 'assets/lottie/nodata_animation.json'

  fonts:
     - family: ComicSans
       fonts:
         - asset: assets/fonts/ComicSansMS3.ttf
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto-Regular.ttf
